version: '3.2'

services:
  eventapi:
    # build: .  # Path to the directory containing the Dockerfile
    image: "startup2023/oeapi:latest"
    ports:
      - "${NESTJS_PORT}:${NESTJS_PORT}"
    # depends_on:
    #   - database
    volumes:
      - ./:/usr/src/app  # Replace with the path where your NestJS app should store persistent data
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - myoeapi_network 
    restart: always

networks:
  myoeapi_network:
    driver: bridge
